### ISSUE TITLE
Train config

### ISSUE THREAD

**Issue by oxcarxierra** [VISION-SJTU/SparseOcc#4]
Thanks for releasing your code! Impressed by your excellent work.
I've encountered some problem with executing dist_train.sh with training config.
Can you share any example of config file? thanks.

**Comment by PinTang1999** [comment]
Thank you for your interest! We have updated the 'docs\train_and_eval.md' to show how to use the config files for training and evaluation.

**Comment by oxcarxierra** [comment]
Great!
