### ISSUE TITLE
FLOPs

### ISSUE THREAD

**Issue by 3bobo** [VISION-SJTU/SparseOcc#5]
How to calculate the FLOPs in `spconv`? The `fvcore` does not support the sparse conv

**Comment by PinTang1999** [comment]
> How to calculate the FLOPs in `spconv`? The `fvcore` does not support the sparse conv

We use `spconv 2.0+`, and we use the utils [here](https://github.com/CVMI-Lab/SparseKD/blob/2e00edef6b94fb208ba64193940bc856e5effbcb/pcdet/utils/common_utils.py#L344) to calculate the FLOPsin `spconv`.

**Comment by 3bobo** [comment]
Thanks for your suggestion! It works.
