### ISSUE TITLE
Asking for some metrics

### ISSUE THREAD

**Issue by jmwang0117** [VISION-SJTU/SparseOcc#6]
Thanks for your excellent work, could you please provide the following three metrics on the SemanticKITTI evaluation set:
1. Number of parameters
2. Recall
3. Precision

**Comment by PinTang1999** [comment]
Thank you for your interest.

Number of parameters: 203.59‬ M
Recall: 58.13
Precision: 58.13

**Comment by PinTang1999** [comment]
Thank you for your interest.

Number of parameters: 203.59‬ M
Recall: 58.13
Precision: 49.77
